Repository lucass023/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#7 Create aquitetura.md
  docs/aquitetura.md
Labels: arquitetura

#9 Integrar implementação v1.0
  src/jogovelha.py
Labels: programação

#11 Integrar testes v1.0
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#12 Gerar release v1.0
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações

#14 #1
  docs/requisitos.md
Labels: análise

#16 V.1.1 arquitetura
  docs/aquitetura.md
  docs/arquitetura.md
Labels: arquitetura

#18 #5
  src/jogodvelha.py
Labels: programação

#21 V1.1
  docs/aquitetura.md
  docs/arquitetura.md
  docs/requisitos.md
  src/jogodvelha.py
  src/testes_iniic.py
  src/testes_jogaar.py
Labels: operações
